services:
  - type: worker
    name: event-runner
    env: docker
    rootDir: event-distributor/bots
    plan: starter
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE
        sync: false
      - key: VITE_SUPABASE_ANON
        sync: false
      - key: SUPABASE_ADMIN_EMAIL
        sync: false
      - key: SUPABASE_ADMIN_PASSWORD
        sync: false
    dockerCommand: "npx tsx supabase-runner.ts"
